spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 431798661063-c15r9hqpq4jeg0f83c0pn2upluub6g7h.apps.googleusercontent.com
            client-secret: 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
            redirect-uri-template: 'http://localhost:8080/login/oauth2/code/google'
            scope:
              - email
              - profile